CREATE TABLE BOOKS(
	ID INT PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	AUTHOR VARCHAR(20) NOT NULL
)

INSERT INTO BOOKS VALUES(1,'HARRY POTTER','JK ROWLING');

ALTER TABLE BOOKS
ADD COUNT INT CHECK(COUNT>=1)

SELECT * FROM BOOKS

UPDATE BOOKS 
SET COUNT=3
WHERE ID = 1

INSERT INTO BOOKS VALUES(2,'GAME OF THRONS','I DONT KNOW ',12);


CREATE TABLE LIBRARY_VISITOR_USER(
	USER_ID INT PRIMARY KEY,
	USER_NAME VARCHAR(20) NOT NULL,
	AGE INT CHECK(AGE>=17) NOT NULL,
	EMAIL_ID VARCHAR(20) UNIQUE NOT NULL
)

INSERT INTO LIBRARY_VISITOR_USER
VALUES(101,'ARYAN',18,'ARD@GMAIL.COM')

INSERT INTO LIBRARY_VISITOR_USER
VALUES(102,'RAMESH',19,'RMD@GMAIL.COM')

SELECT * FROM LIBRARY_VISITOR_USER

INSERT INTO LIBRARY_VISITOR_USER
VALUES(1,'RAM',19,'RAM@GMAIL.COM')

UPDATE LIBRARY_VISITOR_USER
SET USER_ID = 103
WHERE USER_ID =1

ALTER TABLE LIBRARY_VISITOR_USER
ALTER COLUMN EMAIL_ID TYPE VARCHAR(15);

CREATE TABLE BOOK_ISSUE(
	ISSUE_ID INT PRIMARY KEY ,
	BOOK_ID INT REFERENCES BOOKS(ID) NOT NULL,
	USER_ID INT REFERENCES LIBRARY_VISITOR_USER(USER_ID),
	ISSUE_DATE DATE NOT NULL DEFAULT CURRENT_DATE
)

INSERT INTO BOOK_ISSUE
VALUES(121,1,101,'2026-01-09')

SELECT * FROM BOOK_ISSUE


CREATE ROLE LIBRARIAN
WITH LOGIN PASSWORD 'RAKESH101'


GRANT SELECT, INSERT, DELETE, UPDATE ON BOOKS TO LIBRARIAN




REVOKE  SELECT,INSERT,DELETE,INSERT,UPDATE ON BOOKS FROM LIBRANIAN


